**Multi-Dimensional Lists** Multi-dimensional lists are very useful for data manipulation and analysis. Many modules in Python exist (NumPy, Pandas, ...) to assist with this but its always a good idea to understand how to use built-in Python as well!

In [22]:
def makeMatrix():
    r1 = [7, 8, 9]
    r2 = [4, 5, 6]
    r3 = [1, 2, 3]
    return [r1, r2, r3]

**Programming Practice:** Write a Python function that takes as input a 2D list and searches the list for a specific value

In [31]:
def search2D(list, value):
    for i in range(len(list)):
        for j in range(len(list[i])):
            if list[i][j]==value:
                return i, j
    return -1, -1

In [32]:
myList = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(search2D(myList, 4))
print(search2D(myList, 'A'))

(1, 0)
(-1, -1)


**Programming Practice:** Write a Python function that takes as input a 2D list and returns a copy of that list.

In [35]:
def dup2D(list):
    for i in range(len(list)):
        for j in range(len(list[i])):
            list[i][j] *= 2
    return list
    

In [44]:
x = [[1, 2, 3], [4, 5, 6]]
y = dup2D(x)
z = x.copy()

print(x, y)
y[0][0]="A"
print(x, y, z)

[[2, 4, 6], [8, 10, 12]] [[2, 4, 6], [8, 10, 12]]
[['A', 4, 6], [8, 10, 12]] [['A', 4, 6], [8, 10, 12]] [['A', 4, 6], [8, 10, 12]]


**Copying a matrix** A common mistake in using a multi-dimensional list is creating a *shallow* copy of the list.

In [ ]:
import copy

orig = [ [1,2,3], [4, 5, 6]]
not_copy = orig
s_copy = orig[:]
d_copy = copy.deepcopy(orig)

orig[1][1]=9
not_copy[0][0]=8
s_copy[0][2]=7
d_copy[1][2]=10

print(orig)
print(not_copy)
print(s_copy)
print(d_copy)


In [ ]:
def doubleAppend(inList):
    return [inList, inList]

x = doubleAppend([1, 2, 3])
x[0][0]=9
print(x)

**Don't do this when copying multi-dimensional lists:**

In [ ]:
l1 = [ [1, 2], [3, 4] ]
l2 = l1[:]
l3 = l1.copy()

l4 = []

for i in l1:
    l4.append(i)

l1[0][0]=9

print(l1, "*", l2, "*",l3, "*",l4)



**Instead do one of these:**

In [ ]:
import copy
import numpy as np

l1 = [ [1, 2], [3, 4] ]
l2 = copy.deepcopy(l1)

l3 = []
for row in l1:
    tmp = []
    for val in row:
        tmp.append(val)
    l3.append(tmp)

l4 = np.array(l1)

l1[0][0]=9

print(l1, "*", l2, "*", l3, "*",l4)


### Numpy

In [10]:
import numpy as np

In [ ]:
print(np.shape([0])) # (1,)

print(np.shape([[1,2,3],[4,5,6]])) # (2, 3)

myList = []
for i in range(6):
    temp = []
    for j in range(3):
        temp.append(j)
    myList.append(temp)

print(np.shape(myList))

x = np.zeros([5,2])
print(x)
print(np.shape(x)) # (5, 2)

In [ ]:
myArray = np.zeros([1,5])
print(myArray)

In [ ]:
myArray = np.ones([2,2])
print(myArray)

In [ ]:
myArray = np.empty([3,2,1])
print(myArray)

In [ ]:
myArray = np.full([3,2,1], None)
print(myArray)

In [ ]:
myArray = np.linspace(0, 9, 10)
print(myArray)
reshape = np.reshape(myArray,[2,5])
print(reshape)

In [ ]:
a1 = np.zeros([3,3])
a2 = np.linspace(0,8, 9).reshape([3,3])
a1 += 5

print(a1)

print(a1+a2)


In [ ]:
myArray = np.linspace(0, 9, 10)
greater = myArray[myArray > 4]
print(greater)


In [ ]:
myArray = np.linspace(0, 9, 10)
slice = myArray[1:4]
slice[0]=12
print(myArray)

Here are some other useful NumPy functions in action!

In [ ]:
nl = np.arange(4).reshape(2, 2)
nl2 = nl * 2

# Matrix multiplication
# 0*0+1*4     0*0+1*6
# 2*0+3*4     2*2+3*6
print(nl.dot(nl2))

# Unique items
x = np.array([1, 1, 1, 2, 3, 4, 4, 5, 5, 6])
print(np.unique(x))


In [7]:
l = [1, 2, 3, 4, 5, 6, 7]
l.remove(3)
l

[1, 2, 4, 5, 6, 7]

In [3]:
l.pop(3)

4

In [4]:
l.pop(3)

5

In [5]:
l

[1, 2, 3, 6]

In [8]:
for i in range(3):
    print(i)
    

0
1
2


In [19]:
outerList = []
for i in range(3):
    innerList = []
    for j in range(3):
        innerList.append(i+j)
    outerList.append(innerList)
outerList

[[0, 1, 2], [1, 2, 3], [2, 3, 4]]

In [47]:
import numpy as np
x = np.zeros([1, 5])
x

array([[0., 0., 0., 0., 0.]])

In [51]:
x = np.ones([2, 2])
x

array([[1., 1.],
       [1., 1.]])

In [52]:
x = np.full([8, 8], 8)
x

array([[8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8]])